# Generated by Django 4.1.1 on 2022-09-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filme', models.CharField(max_length=60)),
                ('ano', models.BigIntegerField(max_length=4)),
                ('diretor', models.CharField(max_length=40)),
                ('comentarios', models.TextField()),
                ('data_publicacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
